runtime: python311
env: standard
entrypoint: gunicorn -b :$PORT --workers 2 --timeout 500 jobsite.wsgi:application

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10

env_variables:
  DJANGO_SETTINGS_MODULE: jobsite.settings
  GCS_PROJECT_ID: 'jobs-428816'
beta_settings:
  cloud_sql_instances: jobs-428816:us-central

instance_class: F2 

automatic_scaling:
  min_instances: 0
  max_instances: 4
  target_cpu_utilization: 0.8
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
