services:
  - type: web
    name: careerhorizon
    env: python
    plan: free
    buildCommand: "
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate"
    startCommand: "gunicorn jobsite.wsgi"
    envVars:
      - key: DATABASE_URL
        fromFile: .env
      - key: SECRET_KEY
        fromFile: .env
      - key: DEBUG
        fromFile: .env
      - key: GS_BUCKET_NAME
        fromFile: .env
      - key: GCS_TYPE
        fromFile: .env
      - key: GCS_PROJECT_ID
        fromFile: .env
      - key: GCS_PRIVATE_KEY_ID
        fromFile: .env
      - key: GCS_PRIVATE_KEY
        fromFile: .env
      - key: GCS_CLIENT_EMAIL
        fromFile: .env
      - key: GCS_CLIENT_ID
        fromFile: .env
      - key: GCS_AUTH_URI
        fromFile: .env
      - key: GCS_TOKEN_URI
        fromFile: .env
      - key: GCS_AUTH_PROVIDER_CERT_URL
        fromFile: .env
      - key: GCS_CLIENT_CERT_URL
        fromFile: .env